name: Python CI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install tox
        run: sudo apt-get update && sudo apt-get install -y tox
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.tox
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: make env-create
  test:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install tox
        run: sudo apt-get update && sudo apt-get install -y tox
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.tox
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Run Tests
        run: make ci-test
  quality:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install tox
        run: sudo apt-get update && sudo apt-get install -y tox
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.tox
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Lint Code
        run: make ci-lint && make ci-lint-tests
      - name: Check Code Style
        run: make ci-code-style
      - name: Check dependencies
        run: make ci-check-dependencies
      - name: Check for security issues
        run: make ci-security
      - name: Check the code metrics
        run: make ci-code-metrics
